### ISSUE TITLE
TypeError: ('Could not adapt', <FolderishDocument at /Plone/de/dummy>, <SchemaClass plone.restapi.behaviors.IBlocks>)

### ISSUE THREAD

**Issue by tisto** [plone/plone.dexterity#120]
We ran into an issue on Plone 5.2, plone.restapi 5.1.0, and Volto 4 lately:

https://community.plone.org/t/conflict-error-and-could-not-adapt-error-with-volto-and-plone-5-2/11020
https://github.com/plone/plone.restapi/issues/838

We moved all our code and Plone core code we were using to use named behaviors. Though, this did not solve the problem:

````
2019-12-04 10:52:44,400 ERROR   [Zope.SiteErrorLog:251][waitress] 1575453164.4001880.27303118517455216 http://localhost:8080/Plone/de/dummy/asdasdas/GET_application_json_
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 21, in render
  Module plone.restapi.services.content.get, line 18, in reply
  Module plone.restapi.serializer.dxcontent, line 125, in __call__
  Module plone.restapi.serializer.dxcontent, line 83, in __call__
  Module plone.restapi.serializer.dxfields, line 28, in __call__
  Module plone.restapi.serializer.dxfields, line 31, in get_value
TypeError: ('Could not adapt', <FolderishDocument at /Plone/de/dummy>, <SchemaClass plone.restapi.behaviors.IBlocks>)
````

We asked @jensens for help because we are swamped in work and he found a solution in no time:

https://github.com/plone/plone.dexterity/pull/119

**Comment by jensens** [comment]
Well, no time is relative: with project-setup, digging and reading into `zope.interface` and `zope.component` code internals first and given this error was not debugable the classical way it took me 6 hours. It was challenging, but also fun ;)

**Comment by tisto** [comment]
@jensens given that error, 6h still counts as "no time". :)

**Comment by tisto** [comment]
@jensens @pbauer @datakurre FYI: plone.dexterity 2.9.3 released: 

https://pypi.org/project/plone.dexterity/2.9.3/#id1
