### ISSUE TITLE
Import adapter for GenericSetup content error in python 3

### ISSUE THREAD

**Issue by ewohnlich** [plone/plone.dexterity#124]
Both instantiations of StringIO here https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/exportimport.py#L86 error out because these are bytes not str in python 3. The data is passed to methods that expect str not bytes, so StringIO is still the right call over BytesIO, but it needs to be decoded next. For me it was enough to just call `.decode('utf-8')` although probably more appropriate to use the site's encoding. I don't know how you'd want to do this to support both py 2 and 3.

**Comment by tkimnguyen** [comment]
Just ran into this myself. Does that `.decode` call not work in Py 2? A simple `data = str(data)` (hacky, yes) gets me past this error.

**Comment by tkimnguyen** [comment]
@ewohnlich your suggestion works much better :) I'll try to start a PR for this fix

**Comment by ewohnlich** [comment]
Yeah str(data) won't work because it will just turn it into a str with a character b in it, e.g. "b'mydata'". I"m not sure if calling decode works as expected in py2
