### ISSUE TITLE
Behaviors/TTW model should override schema fields/fieldsets not append new ones with the same id

### ISSUE THREAD

**Issue by avoinea** [plone/plone.dexterity#144]
Bellow I enabled 2 behaviors that defines the same fields/fieldsets and manually added the same fields/fieldsets TTW

![multiple-behaviors](https://user-images.githubusercontent.com/323385/108083907-44f38e00-707c-11eb-9e27-94bb76b8f691.png)

Now the edit form looks broken as it provides the Editor 3 instances of the same property.

Expected behavior: 
1. The last enabled behavior should be taken in consideration
2. TTW Model/schema should override the all.

**Comment by avoinea** [comment]
@pbauer Thoughts?!

**Comment by avoinea** [comment]
You can easily replicate the issue by enabling Basic metadata and Dublin Core on the same CType

![basic-dublin](https://user-images.githubusercontent.com/323385/108085046-90f30280-707d-11eb-9c90-2722f298a96a.png)

Output:

![basic-meta-edit](https://user-images.githubusercontent.com/323385/108085088-9ea88800-707d-11eb-9668-62ffb337a652.png)

**Comment by avoinea** [comment]
Having this fixed will allow us to enable IDubinCore behavior for example and override from another behavior only some fields. We will be able to change TTW default values of behavior defined fields just by adding TTW new fields with the same name.

See PR #145

**Comment by ale-rt** [comment]
I see that this is annoying but IMO it is kind of expected, I am not sure we should have some drastic change to fix this behavior.

**Comment by avoinea** [comment]
@ale-rt Then we can handle it as a feature request :smile:

**Comment by mauritsvanrees** [comment]
I fear the way you fix it now, by setting [`ignorePrefix = True`](https://github.com/plone/plone.dexterity/pull/145/files), will break existing code. Any custom edit form that tries `request.form.get("form.widgets.IDublinCore.title")` will not find the title anymore.

This does not sound like a good idea for Plone 5.2 at least.

How it currently works *is* annoying and confusing now that I try it: enable both Dublin core and basic metadata, set different titles in the two title fields, and the second title wins.
But to me this means: you should not do this, it is an error to enable both behaviors. (Done as easy example here, I understand that.)

I can understand the need. I have disabled Dublin core and basic metadata behaviors in a project, and replaced the basic metadata with my own behavior, where I think I only changed the label of the title field. Being able to override a single field instead could be nicer. But also confusing: how do you determine which conflicting behavior wins?

**Comment by avoinea** [comment]
@mauritsvanrees I looked into the code and it builds the schema field by field taking the behaviors top to bottom. Thus, the second behavior field will be skipped if it's already within the first behavior.

It will work as portal_skins used to in the good old times :)

Thus:
1. TTW schema is first
2. Then behaviors top to bottom.

We may need a way to reorder behaviors in Plone/Volto (right now only possible via ZMI).

My proposal is to move this to Plone 6, but I'm not too familiar with it, thus I need guidance.

**Comment by mauritsvanrees** [comment]
@avoinea Is this still on your radar?
I am still not sure if the current PRs are what we want, even for Plone 6. This may fix a use case that we do not want to support. But at some point this should be either pursued further, or abandoned and the issues/PRs closed.

(I am doing package releases now, and in my workflow I see the PRs of a package, and a lot of them include a PR from you related to this.)

**Comment by avoinea** [comment]
@mauritsvanrees This behavior is already in place within plone.restapi, thus I think we should also fix it here. Unfortunately, I've been beaten by Jenkins, I don't know how to proceed.

**Comment by mauritsvanrees** [comment]
I propose to close this issue and all related PRs. Not much has happened the past year, since [my comment](#issuecomment-920070751). Plone 6.0 is close and these changes will not be included.
Sorry for lost work. If you still want to pursue this further, it might be considered for Plone 6.1.

Maybe some of the PRs that change tests could be edited to pass both with the current code and with your proposed change from PR #145. I don't know how difficult that would be, but it would make such a PR in the future easier.

**Comment by mauritsvanrees** [comment]
We are leaving this open for too long, which is not helping anybody...

To rephrase [my first comment above](https://github.com/plone/plone.dexterity/issues/144#issuecomment-808171263) I can see a small use case, but I don't see how we can do this without breaking lots of add-ons. I care more about the add-ons than the use case. So I propose we close this and related PRs and issues.

But I am happy to wait till the end of next week to see if someone wants to pick it up anyway during the Alpine City Sprint.

**Comment by mauritsvanrees** [comment]
I am closing this and the related issues and PRs, for the given reasons.

As said, if we want to pursue this anyway, it may help to already change the tests to work in both cases.  For example, I see tests with this change:

```
- browser.getControl(name='form.widgets.IDublinCore.title').value = "Doc"
+ browser.getControl(name='form.widgets.title').value = "Doc"
```

The following, or something similar, should work in both cases (untested):

```
control = browser.getControl(name='form.widgets.IDublinCore.title')
# We may need to catch a KeyError or so instead.
if control is None:
    control = browser.getControl(name='form.widgets.title')
control.value = "Doc"
```
