### ISSUE TITLE
portal setup snapshot broken - filerepresentation leads to "RuntimeError: maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by simahawk** [plone/plone.dexterity#23]
I get this when trying to create a snapshot. 
Plone-4.3.2
Products.GenericSetup-1.7.4
plone.app.dexterity-2.0.11
plone.dexterity-2.2.1
plone.rfc822-1.1

2015-02-02 11:16:02 ERROR Zope.SiteErrorLog 1422872162.790.393378694879 http://localhost:8080/Plone/portal_setup/manage_createSnapshot
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Products.GenericSetup.tool, line 712, in manage_createSnapshot
  Module Products.GenericSetup.tool, line 389, in createSnapshot
  Module Products.CMFCore.exportimport.content, line 31, in exportSiteStructure
  Module Products.CMFCore.exportimport.content, line 132, in export
  Module plone.dexterity.exportimport, line 74, in export
  Module plone.dexterity.filerepresentation, line 105, in manage_FTPget
  Module plone.dexterity.filerepresentation, line 602, in size
  Module plone.memoize.instance, line 51, in memogetter
  Module plone.dexterity.filerepresentation, line 627, in _getStream
  Module email.generator, line 83, in flatten
  Module email.generator, line 115, in _write
  Module email.generator, line 148, in _write_headers
  Module email.header, line 407, in encode
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
  Module email.header, line 332, in _split
RuntimeError: maximum recursion depth exceeded

**Comment by datakurre** [comment]
Could this be caused by by some DX file field not properly marked as primary field in schema?

AFAIK, it would cause field to be marshaled into a email.message.Message header (instead of a payload), which could cause too deep recursion, because email.header splits strings into multiple lines using a recursive algorithm.

**Comment by simahawk** [comment]
ok, so I need to find out which object is breaking and check its schema. Tnx for the pointer!

**Comment by simahawk** [comment]
looks like the export is broken on my DX object "AdvancedPage".
There's no file field... the schema is this: https://github.com/simahawk/collective.advancedpage/blob/master/collective/advancedpage/interfaces.py
Could it be because I'm using "lead image behavior"?
It's interfaces declares a NamedBlobImage field: https://github.com/plone/plone.app.contenttypes/blob/master/plone/app/contenttypes/behaviors/leadimage.py

**Comment by simahawk** [comment]
I did a test by marking the 'body' field as 'primary' 
https://github.com/simahawk/collective.advancedpage/commit/c7c5d86cc4542c2dc23e8bdacb0378b1c7b387e0
as suggested here
http://docs.plone.org/external/plone.app.dexterity/docs/reference/form-schema-hints.html

And... it looks like is working right now :)

Tnx @datakurre :)

**Comment by simahawk** [comment]
BTW: should we say somewhere in the doc that having a "primary" field for custom content types is a must-have?

**Comment by datakurre** [comment]
@simahawk Yes. Also file and issue for LeadImage. Basically all Blob fields (and object fields like RichText) should be primary fields (multiple primary fields are allowed) to support marshalling (snapshots and plone.rfc822).

Yet, there must be reason, why primary fields are opt-in instead of making those fields types implement IPrimaryField by default.
