### ISSUE TITLE
Get rid of plone.mocktestcase

### ISSUE THREAD

**Issue by jensens** [plone/plone.dexterity#30]
because it makes writing tests a nightmare.

**Comment by datakurre** [comment]
But is there to make running tests fast? Or to be replaced with some better mock library?

**Comment by jensens** [comment]
i think it was just a decision at the time of writing. 
the mock library available in python 3 stdlib and in 2.7 as package would be my first choice these days.

**Comment by gforcada** [comment]
I wouldn't call it an enhancement tbh, cleanup suits more I would say ... :)

**Comment by datakurre** [comment]
:+1:

**Comment by jensens** [comment]
an enhancement for everone writing tests.... well, sure, cleanup fits too and better. but there were no such label. OT here, but see also https://community.plone.org/t/our-issue-label-chaos/676/4

**Comment by davisagli** [comment]
This was done a while ago; we use `mock` now instead.
