### ISSUE TITLE
++widget++ traversal doesn't work for Add Forms

### ISSUE THREAD

**Issue by gweis** [plone/plone.dexterity#40]
When using ++widget++ traversal on AddForms (plone.dexterity.browser.add.DefaultAddForm), update is being called while the user is not yet authenticated. Since commit d240bb2dd81971358baf65ab134bdcf3494414d3 update tries to verify allowed content types on the context which is always empty for unauthenticated users, and will therefore always throw a ValueError.

I can think of 3 possible solutions.
- Don't allow widget traversal on add forms
- check the request with plone.z3cform.interfaces.IDeferSecurityCheck in update
- do the allowed content type check later (maybe in add(..) ? )

**Comment by alecpm** [comment]
I believe this is now fixed (with tests) on master.
