### ISSUE TITLE
Save default values for behavior's fields

### ISSUE THREAD

**Issue by Martronic-SA** [plone/plone.dexterity#54]
It should be possible to save the default values for the fields coming from the behaviors defined in the DX content type.
I think that the getAdditionalSchemata method of plone.dexterity utils should retrieve the default value stored somewhere in the DexterityFTI and set it as default for the fields.
The default values could be stored in the DexterityFTI as a dict of key/value that would be updated when new default values are defined by the user.

What do you think of it?

**Comment by jensens** [comment]
fixed long time ago a bit differently with https://github.com/plone/plone.dexterity/pull/67
just they wont be updated but the status on save is set. 
which is imo fine

**Comment by gforcada** [comment]
Actually, a huge performance improvement would be to store the values themselves, as @datakurre pointed out in https://github.com/plone/plone.dexterity/issues/98#issuecomment-478047161
