### ISSUE TITLE
Possible recursion error

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.dexterity#63]
See https://github.com/collective/collective.loremipsum/issues/6
I don't know if this is something in collective.loremipsum or in plone.dexterity.

**Comment by davisagli** [comment]
This may have been fixed by https://github.com/plone/plone.registry/pull/11

**Comment by mauritsvanrees** [comment]
That seems like it should work, yes.
Also, when I tried the same thing again, I could not reproduce this.
