### ISSUE TITLE
plone.app.uuid isn't declared as dependency

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.dexterity#86]
```plone.app.uuid``` is [used](https://github.com/plone/plone.dexterity/blob/bad83e4e81d83fe04d9f73b54851de055c2ff7d9/plone/dexterity/utils.py#L6) but isn't declared as dependency in [setup.py](https://github.com/plone/plone.dexterity/blob/242a6272043e344a4fdc38ee5ebcd76f7669cc22/setup.py#L39). This occurs in the ```master``` and branch ```2.2.x```.

**Comment by Coder-aadarsh** [comment]
Its solved - plone.app.uuid is declared as a dependency in the install_requires section of the setup.py script.
